openapi: 3.0.3
info:
  title: API de Usuários
  version: 1.0.0
  description: API para cadastro e listagem de usuários

servers:
  - url: https://api.exemplo.com/v1

paths:
  /users:
    get:
      summary: Lista todos os usuários
      responses:
        '200':
          description: Lista de usuários
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'

    post:
      summary: Cadastra um novo usuário
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: Usuário criado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

components:
  schemas:
    User:
      $ref: 'https://raw.githubusercontent.com/ecaraujo/api-specs/main/schemas/User.yaml'
